Mozilla-Campus-Club-IIT/Hello-World-Collection

collection/HTML_saidHello.html

added html hello world

---

collection/HTML_saidHello.html

created a hello world program using html

created a hello world using html

---

collection/Go_saidHello.go

Add Go version

---

collection/CoffeeScript_saidHello.coffee
collection/Elixir_saidHello.ex

I have created Elixir_saidHello.ex #48 and CoffeeScript_saidHello.coffee #31.

Added Elixir_saidHello.ex #48

---

collection/Coldfusion_saidHello.cfm

Added Coldfusion markup language entry for Hello world

Added Coldfusion markup language entry for Hello world

---

collection/CSS_saidHello.css

CSS says hello!

---

collection/Lua_saidHello.lua

Adding Lua language Issue #87.

Adding Hello World by Lua

---

collection/C++_saidHello.cpp

completed the code so can be used as error free

completed the code

---

collection/JavaFX_saidHello.java

Added JavaFX Hello World

---

collection/Java_saidHello.java

clarified the code for visually and completed the syntaxes

clarified and completed

---

collection/Nim_saidHello.nim
collection/OCaml_saidHello.ml

Add Nim and OCaml's Hello World

---

collection/TrumpScript_saidHello.tr

added hello world for TrumpScript

---

collection/PowerShell_saidHello_1.ps1

Hello World by PowerShell #105

---

collection/SCSS_saidHello.scss

Hello World by SCSS #114

---

collection/SwiftPlayground_saidHello.playground/Contents.swift
collection/SwiftPlayground_saidHello.playground/contents.xcplayground

Add SwiftPlayground_saidHello.playground file using Xcode 9
Resolve #16

Hello World by Swift Playground #16

---

collection/Logo_saidHello.logo

added hello world for logo

---

collection/Julia_saidHello.jl

added hello world using Julia

---

collection/C_shell_saidHello.csh

Add the Hello World program written in Microsoft C Shell language.

Create C Shell "Hello World" program

---

collection/Ionic_saidHello.html

Added HTML file Ionic Hello World Program to collection folder under file name Ionic_saidHello.html

Added Ionic_saidHello.html to collection

---

Assembly_saidHello.asm

Add MIPS Assembly version

---

collection/D_saidHello.d

This is a 'hello world' written in the D language, closing #40

D language hello world

---

collection/JavaScript_saidHello_2.js

I added an alternative way of saying "Hello World" in JS.

Added alternative JS file

---

collection/CommonLisp_saidHello.cl

Added CommonLisp

---

collection/Delphi_saidHello.pas

Added Hello world Delphi

---

collection/Assember_saidHello.asm

Added Hello world assembly language

Added Hello world assembly language

---

collection/Clipper_saidHello.prg

Added Hello world Clipper

---

collection/VueJS_saidHello.html

Added Hello world VueJS

---

collection/4test.bat
collection/4test_saidHello.bat

Added  Hello world in 4test

---

collection/1c-enterprise_saidHello.cfl
collection/Apl-probe_saidHello.apl

Added  Hello world in Apl

---

collection/1c-enterprise_saidHello.cfl

Added  Hello world in 1c

---

collection/1c-enterprise_saidHello.cfl
collection/fortran77_saidHello.f

Added  Hello world in Fortran

---

collection/1c-enterprise_saidHello.cfl
collection/fortran90_saidHello.f90

Added  Hello world in Fortran90

Added  Hello world in Fortran90

---

collection/1c-enterprise_saidHello.cfl
collection/abc_saidHello.abc

Added  Hello world in Abc

---

collection/1c-enterprise_saidHello.cfl
collection/acpi_saidHello

Added  Hello world in Acpi
